### ISSUE TITLE
Error with R command for cloning the repo

### ISSUE THREAD

**Issue by schmaluk** [okgreece/TimeSeries.OBeu#1]
Hello @kleanthisk10,
I was trying to install this app into DAM. Not familiar with R.

I have a file with the commands from the manual:
install.packages("devtools",repos = "http://cran.us.r-project.org");
library(devtools);
install_github(TimeSeries.OBeu);

And execute this file with: RUN Rscript /install.R
But getting this error back:
Error in lapply(repo, github_remote, username = username, ref = ref, subdir = subdir,  : 
  object 'TimeSeries.OBeu' not found
Calls: install_github -> lapply
Execution halted

Thanks

**Comment by schmaluk** [comment]
Will figure it out myself I guess. But thanks

**Comment by kleanthisk10** [comment]
Hi @mlukasch 
Try install_github("okgreece/TimeSeries.OBeu")

**Comment by kleanthisk10** [comment]
@mlukasch you can try it directly with opencpu (updated read me file)
